export const SET_SELECTED_AVATAR = "SET_SELECTED_AVATAR";
export const ADD_AVATAR = "ADD_AVATAR";
export const UPDATE_AVATAR = "UPDATE_AVATAR";
export const DELETE_AVATAR = "DELETE_AVATAR";
export const LOAD_AVATARS = "LOAD_AVATARS";
export const REPLACE_AVATAR = "REPLACE_AVATAR";
export const ADD_SELECTED_AVATAR = "ADD_SELECTED_AVATAR";
export const DELETE_SELECTED_AVATAR = "DELETE_SELECTED_AVATAR";

export const LOAD_USER = "LOAD_USER";
export const LOAD_PROFILE = "LOAD_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const SHOW_BARSIDE = "SHOW_BARSIDE";
export const HIDE_BARSIDE = "HIDE_BARSIDE";

export const SET_DEV_SECTION = "SET_DEV_SECTION";
